# Numpy Assignment

In [14]:
import numpy as np

In [18]:
def vander_mat(vector, N = None, increasing = False):
    '''Function or generator is used to create a matrix of row elements in geometric series called Alexandre
    Theophile Vandermonde matrix.
    Function arguments-Input 1-D vector & Number of columns of Alexandre Theophile
    Vandermonde matrix'''
    if N == None:
        N = len(vector)
        if increasing == False:
            vand_matrix = np.mat(np.array([vec ** (N-i-1) for vec in vector for i in range(N)]))
            vand_matrix = vand_matrix.reshape(vector.size,N)
            print("Alexandre Theophile Vandermonde matrix of column %d, increasing False"%N,'\n','--'*25)
            print(vand_matrix,'\n')
        elif increasing == True:
            vand_matrix = np.mat(np.array([vec ** i for vec in vector for i in range(N)]))
            vand_matrix = vand_matrix.reshape(vector.size,N)
            print("Alexandre Theophile Vandermonde matrix of column %d, increasing True"%N,'\n','--'*25)
            print(vand_matrix,'\n')
    else:
        if increasing == False:
            vand_matrix = np.mat(np.array([vec ** (N-i-1) for vec in vector for i in range(N)]))
            vand_matrix = vand_matrix.reshape(vector.size,N)
            print("Alexandre Theophile Vandermonde matrix of column %d, increasing False"%N,'\n','--'*35)
            print(vand_matrix,'\n')
        else:
            vand_matrix = np.mat(np.array([vec ** i for vec in vector for i in range(N)]))
            vand_matrix = vand_matrix.reshape(vector.size,N)
            print("Alexandre Theophile Vandermonde matrix of column %d, increasing True"%N,'\n','--'*35)
            print(vand_matrix,'\n')
        
# Calling Function
input_vector =np.array([1,2,3,4,5])
col_output_matrix = 3
print("Input 1-D vector",'\n','--'*25)
print(input_vector,'\n')
print("Column of Vandermonde matrix",'\n','--'*25)
print(col_output_matrix,'\n')
vander_mat(input_vector, N = col_output_matrix, increasing =False)
vander_mat(input_vector, N = col_output_matrix, increasing =True)      
   

Input 1-D vector 
 --------------------------------------------------
[1 2 3 4 5] 

Column of Vandermonde matrix 
 --------------------------------------------------
3 

Alexandre Theophile Vandermonde matrix of column 3, increasing False 
 ----------------------------------------------------------------------
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Alexandre Theophile Vandermonde matrix of column 3, increasing True 
 ----------------------------------------------------------------------
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



In [16]:
def movi_avg(seq,k):
    # seq- 1-D given sequence in array
    # k (K>0), window size
    n = len(seq)
    m = n-k+1
    mov_avg = np.empty((1,m))
    for i in range(n+1):
        if i-k >= 1:
            mov_avg[0][0] = seq[0:k].mean()
            mov_avg[0][i-k] = seq[i-k:i].mean()
            #return mov_avg
    print("Number of moving average sequence",'\n','--'*25)
    print("n-k+1: ",n-k+1,'\n')
    print("moving average sequence array",'\n','--'*35)
    print(mov_avg)

#Test sequenece & window size
seq =np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k =3
#Calling Function
movi_avg(seq,k)



Number of moving average sequence 
 --------------------------------------------------
n-k+1:  11 

moving average sequence array 
 ----------------------------------------------------------------------
[[  5.           4.66666667   5.66666667   6.66666667   9.66666667
   28.66666667  49.33333333  72.66666667  84.          93.33333333
  116.33333333]]
